# Generated by Django 5.1.2 on 2024-10-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_clients_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='login.clients')),
            ],
            options={
                'verbose_name': 'Token de Cliente',
                'verbose_name_plural': 'Tokens de Clientes',
                'db_table': 'client_token',
            },
        ),
    ]
