# Generated by Django 5.1.2 on 2024-10-23 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_clienttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttoken',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.clients'),
        ),
    ]
