# Generated by Django 5.1.2 on 2024-10-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_clienttoken_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='db_user',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre de usuario'),
            preserve_default=False,
        ),
    ]
